services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./server"]
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  app-1-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./worker"]
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  app-2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./app2"]
    ports:
      - "9090:9090"

  postgres:
    image: postgis/postgis:18-3.6
    env_file:
      - .env
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    
    ports:
      - "6379:6379"